---
- name: Deploy Flask webserver
  remote_user: root 
  become: yes
  become_method: sudo
  hosts: local 
  gather_facts: False
  
  tasks:
    - name: Install virtualenv 
      yum: name=python-virtualenv state=present

    - name: Create virtual environment
      shell: "virtualenv /home/ec2-user/Enterprise-Software/env"

    - name: Activate virtual environment
      shell: "source /home/ec2-user/Enterprise-Software/env/bin/activate"

    - name: Install Flask
      shell: "pip install flask flask-sso"

    - name: Deploy Flask on port 80
      shell: "nohup python /home/ec2-user/Enterprise-Software/project/app.py"
