---
- name: Deploy Flask webserver
  remote_user: root 
  become: yes
  become_method: sudo
  hosts: local 
  gather_facts: False
  
  tasks:
    - name: Install virtualenv 
      yum: name=python-virtualenv state=present

    - name: Create and activate virtual environment
      file: path=/home/ec2-user/Enterprise-Software/hw1/env state=directory

    - name: Install Flask
      shell: "pip install flask"

    - name: Deploy Flask on port 80
      shell: "python /home/ec2-user/Enterprise-Software/hw1/app.py"
