---
- name: Undeploy Flask webserver
  remote_user: root 
  become: yes
  become_method: sudo
  hosts: local 
  gather_facts: False
  
  tasks:
    - name: Terminate Flask webserver process
      shell: "ps ax | grep -v grep | grep app.py | cut -f1 -d ' ' | xargs sudo kill"

    - name: Remove virtual environment
      file:
        path: /home/ec2-user/Enterprise-Software/env
        state: absent

    - name: Uninstall virtualenv 
      yum: name=python-virtualenv state=absent
